<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AdvancedBuildingControl</AssemblyName>
    <AssemblyTitle>Advanced Building Control</AssemblyTitle>
    <Version>2.2.5</Version>
    <PublishConfigurationPath>Properties\PublishConfiguration.xml</PublishConfigurationPath>
  </PropertyGroup>
  <!--Imports must be after PropertyGroup block-->
  <Import Project="$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.User'))\Mod.props" />
  <Import Project="$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.User'))\Mod.targets" />
  <Import Project="$(CS2_STARQ_SHARED_PATH)\StarQ.Shared.projitems" Label="Shared" />
  <Import Project="$(CS2_STARQ_SHARED_PATH)\StarQ.Shared.props" />
  <Import Project="$(CS2_STARQ_SHARED_PATH)\StarQ.Shared.targets" />
</Project>
